#!/usr/bin/env bash

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo "AWS_ACCESS_KEY_ID must be set"
  HAS_ERRORS=true
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
  echo "AWS_SECRET_ACCESS_KEY must be set"
  HAS_ERRORS=true
fi

if [ -z "$S3BUCKET" ]; then
  echo "S3BUCKET must be set"
  HAS_ERRORS=true
fi

if [ $HAS_ERRORS ]; then
  echo "Exiting.... "
  exit 1
fi

if [ -z "$MYSQL_USER" ]; then
  MYSQL_USER='root'
fi

if [ -z "$MYSQL_PASSWORD" ]; then
  MYSQL_PASSWORD='password'
fi

if [ -z "$MYSQL_HOST" ]; then
  MYSQL_HOST='mysql'
fi

if [ -z "$FILEPREFIX" ]; then
  FILEPREFIX='backup'
fi

FILENAME=$FILEPREFIX.latest.sql.gz

aws s3api get-object --bucket $S3BUCKET --key $FILENAME latest.sql.gz
if [ -e latest.sql.gz ] ; then
    gunzip latest.sql.gz
    cat latest.sql | mysql --protocol tcp -u $MYSQL_USER -h $MYSQL_HOST -p$MYSQL_PASSWORD
    echo "Cleaning up..."
    rm latest.sql
else
    echo "No backup to restore"
fi